
// This file has been generated by the GUI designer. Do not modify.
namespace ContaBanco
{
	public partial class Cadastro
	{
		private global::Gtk.Table table1;

		private global::Gtk.Entry cmpCodigo;

		private global::Gtk.Entry cmpCpf;

		private global::Gtk.Entry cmpNome;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnSalvar;

		private global::Gtk.Button btnSair;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ContaBanco.Cadastro
			this.Name = "ContaBanco.Cadastro";
			this.Title = global::Mono.Unix.Catalog.GetString("Cadastro");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ContaBanco.Cadastro.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(18));
			// Container child table1.Gtk.Table+TableChild
			this.cmpCodigo = new global::Gtk.Entry();
			this.cmpCodigo.WidthRequest = 350;
			this.cmpCodigo.CanFocus = true;
			this.cmpCodigo.Name = "cmpCodigo";
			this.cmpCodigo.IsEditable = true;
			this.cmpCodigo.InvisibleChar = '•';
			this.table1.Add(this.cmpCodigo);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.cmpCodigo]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cmpCpf = new global::Gtk.Entry();
			this.cmpCpf.CanFocus = true;
			this.cmpCpf.Name = "cmpCpf";
			this.cmpCpf.IsEditable = true;
			this.cmpCpf.InvisibleChar = '•';
			this.table1.Add(this.cmpCpf);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.cmpCpf]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cmpNome = new global::Gtk.Entry();
			this.cmpNome.CanFocus = true;
			this.cmpNome.Name = "cmpNome";
			this.cmpNome.IsEditable = true;
			this.cmpNome.InvisibleChar = '•';
			this.table1.Add(this.cmpNome);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.cmpNome]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSalvar = new global::Gtk.Button();
			this.btnSalvar.WidthRequest = 120;
			this.btnSalvar.CanFocus = true;
			this.btnSalvar.Name = "btnSalvar";
			this.btnSalvar.UseUnderline = true;
			this.btnSalvar.Label = global::Mono.Unix.Catalog.GetString("Salvar");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.btnSalvar.Image = w4;
			this.hbox1.Add(this.btnSalvar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSalvar]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSair = new global::Gtk.Button();
			this.btnSair.WidthRequest = 120;
			this.btnSair.CanFocus = true;
			this.btnSair.Name = "btnSair";
			this.btnSair.UseUnderline = true;
			this.btnSair.Label = global::Mono.Unix.Catalog.GetString("Sair");
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.btnSair.Image = w6;
			this.hbox1.Add(this.btnSair);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSair]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.table1.Add(this.hbox1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nome:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("CPF:");
			this.label2.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 70;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Código:");
			this.label3.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 476;
			this.DefaultHeight = 168;
			this.Show();
			this.btnSair.Clicked += new global::System.EventHandler(this.OnBtnSairClicked);
			this.btnSalvar.Clicked += new global::System.EventHandler(this.OnBtnSalvarClicked);
		}
	}
}
