
// This file has been generated by the GUI designer. Do not modify.
namespace ContaBanco
{
	public partial class Saque
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label20;

		private global::Gtk.Label lblNome;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label14;

		private global::Gtk.Entry cmpValor;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnSair;

		private global::Gtk.Button btnConfirma;

		private global::Gtk.Statusbar statusbar1;

		private global::Gtk.Label label17;

		private global::Gtk.Label lblAtual;

		private global::Gtk.Label label15;

		private global::Gtk.Label lblDepois;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ContaBanco.Saque
			this.Name = "ContaBanco.Saque";
			this.Title = global::Mono.Unix.Catalog.GetString("Saque");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-cut", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(15));
			// Container child ContaBanco.Saque.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Nome:");
			this.hbox4.Add(this.label20);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label20]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblNome = new global::Gtk.Label();
			this.lblNome.Name = "lblNome";
			this.lblNome.Xalign = 1F;
			this.lblNome.LabelProp = global::Mono.Unix.Catalog.GetString("label21");
			this.hbox4.Add(this.lblNome);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblNome]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Valor:");
			this.hbox3.Add(this.label14);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label14]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cmpValor = new global::Gtk.Entry();
			this.cmpValor.CanFocus = true;
			this.cmpValor.Name = "cmpValor";
			this.cmpValor.IsEditable = true;
			this.cmpValor.InvisibleChar = '•';
			this.hbox3.Add(this.cmpValor);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cmpValor]));
			w5.Position = 1;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSair = new global::Gtk.Button();
			this.btnSair.WidthRequest = 150;
			this.btnSair.CanFocus = true;
			this.btnSair.Name = "btnSair";
			this.btnSair.UseUnderline = true;
			this.btnSair.Label = global::Mono.Unix.Catalog.GetString("Sair");
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
			this.btnSair.Image = w7;
			this.hbox2.Add(this.btnSair);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSair]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnConfirma = new global::Gtk.Button();
			this.btnConfirma.WidthRequest = 150;
			this.btnConfirma.CanFocus = true;
			this.btnConfirma.Name = "btnConfirma";
			this.btnConfirma.UseUnderline = true;
			this.btnConfirma.Label = global::Mono.Unix.Catalog.GetString("Confirmar saque");
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.btnConfirma.Image = w9;
			this.hbox2.Add(this.btnConfirma);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnConfirma]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Saldo Atual:");
			this.statusbar1.Add(this.label17);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label17]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblAtual = new global::Gtk.Label();
			this.lblAtual.Name = "lblAtual";
			this.lblAtual.LabelProp = global::Mono.Unix.Catalog.GetString("label16");
			this.statusbar1.Add(this.lblAtual);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.lblAtual]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(10));
			// Container child statusbar1.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Saldo após saque:");
			this.statusbar1.Add(this.label15);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label15]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblDepois = new global::Gtk.Label();
			this.lblDepois.Name = "lblDepois";
			this.lblDepois.LabelProp = global::Mono.Unix.Catalog.GetString("label13");
			this.statusbar1.Add(this.lblDepois);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.lblDepois]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(10));
			this.vbox1.Add(this.statusbar1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 140;
			this.Show();
			this.cmpValor.TextInserted += new global::Gtk.TextInsertedHandler(this.OnCmpValorTextInserted);
			this.btnConfirma.Clicked += new global::System.EventHandler(this.OnBtnConfirmaClicked);
			this.btnSair.Clicked += new global::System.EventHandler(this.OnBtnSairClicked);
		}
	}
}
