
// This file has been generated by the GUI designer. Do not modify.
namespace ContaBanco
{
	public partial class Deposito
	{
		private global::Gtk.Table table1;

		private global::Gtk.Entry cmpValor;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnConfirma;

		private global::Gtk.Button btnSair;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		private global::Gtk.Label labelNome;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ContaBanco.Deposito
			this.Name = "ContaBanco.Deposito";
			this.Title = global::Mono.Unix.Catalog.GetString("Depósito");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_mail-send-receive", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child ContaBanco.Deposito.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(27));
			// Container child table1.Gtk.Table+TableChild
			this.cmpValor = new global::Gtk.Entry();
			this.cmpValor.WidthRequest = 250;
			this.cmpValor.CanFocus = true;
			this.cmpValor.Name = "cmpValor";
			this.cmpValor.IsEditable = true;
			this.cmpValor.InvisibleChar = '•';
			this.table1.Add(this.cmpValor);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.cmpValor]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnConfirma = new global::Gtk.Button();
			this.btnConfirma.CanFocus = true;
			this.btnConfirma.Name = "btnConfirma";
			this.btnConfirma.UseUnderline = true;
			this.btnConfirma.Label = global::Mono.Unix.Catalog.GetString("Confirmar Depósito");
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_new-spreadsheet", global::Gtk.IconSize.Menu);
			this.btnConfirma.Image = w2;
			this.hbox1.Add(this.btnConfirma);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnConfirma]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSair = new global::Gtk.Button();
			this.btnSair.WidthRequest = 150;
			this.btnSair.CanFocus = true;
			this.btnSair.Name = "btnSair";
			this.btnSair.UseUnderline = true;
			this.btnSair.Label = global::Mono.Unix.Catalog.GetString("Sair");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
			this.btnSair.Image = w4;
			this.hbox1.Add(this.btnSair);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSair]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.table1.Add(this.hbox1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nome:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Valor:");
			this.label3.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNome = new global::Gtk.Label();
			this.labelNome.Name = "labelNome";
			this.labelNome.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.table1.Add(this.labelNome);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.labelNome]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 397;
			this.DefaultHeight = 145;
			this.Show();
			this.btnConfirma.Clicked += new global::System.EventHandler(this.OnBtnConfirmaClicked);
			this.btnSair.Clicked += new global::System.EventHandler(this.OnBtnSairClicked);
		}
	}
}
