
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action helpAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button btnCadastro;

	private global::Gtk.Button btnExcluir;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView viewContas;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Button btnDeposito;

	private global::Gtk.Button btnSaque;

	private global::Gtk.Button btnExtrato;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.helpAction = new global::Gtk.Action("helpAction", null, null, "gtk-help");
		w1.Add(this.helpAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Conta Bancária");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-bold", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnCadastro = new global::Gtk.Button();
		this.btnCadastro.CanFocus = true;
		this.btnCadastro.Name = "btnCadastro";
		this.btnCadastro.UseUnderline = true;
		this.btnCadastro.Label = global::Mono.Unix.Catalog.GetString("Cadastro");
		this.hbox1.Add(this.btnCadastro);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCadastro]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnExcluir = new global::Gtk.Button();
		this.btnExcluir.CanFocus = true;
		this.btnExcluir.Name = "btnExcluir";
		this.btnExcluir.UseUnderline = true;
		this.btnExcluir.Label = global::Mono.Unix.Catalog.GetString("Excluir");
		this.hbox1.Add(this.btnExcluir);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnExcluir]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.viewContas = new global::Gtk.NodeView();
		this.viewContas.TooltipMarkup = "Store";
		this.viewContas.CanFocus = true;
		this.viewContas.Name = "viewContas";
		this.viewContas.Reorderable = true;
		this.viewContas.RulesHint = true;
		this.GtkScrolledWindow.Add(this.viewContas);
		this.hbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
		w6.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnDeposito = new global::Gtk.Button();
		this.btnDeposito.CanFocus = true;
		this.btnDeposito.Name = "btnDeposito";
		this.btnDeposito.UseUnderline = true;
		this.btnDeposito.Label = global::Mono.Unix.Catalog.GetString("Depósito");
		this.vbox3.Add(this.btnDeposito);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.btnDeposito]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnSaque = new global::Gtk.Button();
		this.btnSaque.CanFocus = true;
		this.btnSaque.Name = "btnSaque";
		this.btnSaque.UseUnderline = true;
		this.btnSaque.Label = global::Mono.Unix.Catalog.GetString("Saque");
		this.vbox3.Add(this.btnSaque);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.btnSaque]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnExtrato = new global::Gtk.Button();
		this.btnExtrato.CanFocus = true;
		this.btnExtrato.Name = "btnExtrato";
		this.btnExtrato.UseUnderline = true;
		this.btnExtrato.Label = global::Mono.Unix.Catalog.GetString("Extrato");
		this.vbox3.Add(this.btnExtrato);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.btnExtrato]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w11.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 522;
		this.DefaultHeight = 385;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnCadastro.Clicked += new global::System.EventHandler(this.OnBtnCadastroClicked);
		this.btnExcluir.Clicked += new global::System.EventHandler(this.OnBtnExcluirClicked);
		this.btnDeposito.Clicked += new global::System.EventHandler(this.OnBtnDepositoClicked);
		this.btnSaque.Clicked += new global::System.EventHandler(this.OnBtnSaqueClicked);
		this.btnExtrato.Clicked += new global::System.EventHandler(this.OnBtnExtratoClicked);
	}
}
